spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/membercertification
    username: jjeong
    password: 0525

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true

  thymeleaf:
    cache: false

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG