spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/membercertification
    username: jjeong
    password: 1015

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  thymeleaf:
    cache: false